MY_CONSUMER_KEY = os.environ['CONSUMER_KEY']
MY_CONSUMER_SECRET = os.environ['CONSUMER_SECRET']
MY_ACCESS_TOKEN_KEY = os.environ['ACCESS_TOKEN_KEY']
MY_ACCESS_TOKEN_SECRET = os.environ['ACCESS_TOKEN_SECRET']

SEARCH_QUERY = os.environ['SEARCH_QUERY']
RESPONSE = os.environ['RESPONSE']